import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '../components/Navbar'
import Dashboard from '../components/Dashboard'
import AboutMe from '../components/AboutMe'
import SocialBox from '../components/SocialBox'
import {useTheme} from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Magnús Atli Gylfason | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/magLogoWhite.png" />
      </Head>
    <Navbar></Navbar>
    <Dashboard></Dashboard>
    <AboutMe></AboutMe>
    <SocialBox></SocialBox>
    </div>
  )
}
